In [13]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [14]:
!pip install pandas


Defaulting to user installation because normal site-packages is not writeable


In [15]:
import numpy
numpy.__version__

'1.24.3'

In [16]:
import numpy as np

In [17]:
arr=np.array(10)
arr.ndim #to see dimension of array

0

In [18]:
#make one d array and all functions used on it
oneDarray=np.array([10,23,45,56,67,78])
print(oneDarray)
print(oneDarray.ndim)
print(oneDarray.shape)
print(oneDarray.size)

[10 23 45 56 67 78]
1
(6,)
6


In [19]:
#make two d array and all functions used on it
twoDarr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoDarr.ndim)
print(twoDarr)
print(twoDarr.shape)
print(twoDarr.size)

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


In [20]:
#one d zero array
zerosarr=np.zeros(9,dtype=int)
zerosarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
#2d zeros array
zero2d=np.zeros((2,3))
zero2d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#3d array
threearr=np.zeros((2,3,4))
threearr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
onedones=np.ones(9)
onedones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
#to reshape the array
#reshape is done perfectly
#7 element array cannot be reshaped into 2x3 array)
#reshape only gives view , does not effect actual array
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
arr1.reshape((3,3))

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#make array with constant values
np.full((3,3),9)
#identity matric
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
#generate an array having 10 random values between 0 to 1
np.random.rand(10)



array([0.9192533 , 0.85435556, 0.73980942, 0.57265986, 0.52906726,
       0.46337767, 0.68056516, 0.50070555, 0.2487709 , 0.7343899 ])

In [27]:
np.random.rand()

0.9264206079147034

In [28]:
np.random.rand(9).reshape((3,3))

array([[0.47336223, 0.15559229, 0.43697516],
       [0.30817742, 0.72303222, 0.91085071],
       [0.45089484, 0.95313703, 0.05272039]])

In [29]:
#generate random value in between a given range
np.random.randint(1,10)


4

In [30]:
#generate a dice
dice=np.random.randint(1,7)
print(dice)

3


In [57]:
#rock paper scissors
score_u,score_c=0,0
b=[0,'Rock','paper','scissors']
t=10
while t>0:
    comp=np.random.randint(1,4)
    user=int(input("enter 1 for rock 2 for paper and 3 for scissors"))
    if user==comp:
        print("Tie")
        print("Your score-")
        print(f"User Score-{score_u} amd Computer Score- {score_c}")
    elif(user==1 and comp==3)or(user==2 and comp==1)or(user==3 and comp==2):
        print("User wins")
        score_u=score_u+1
        print("Your score-")
        print(f"User Score-{score_u} amd Computer Score- {score_c}")
    else:
        print("Computer wins")
        score_c=score_c+1
        print("Your score-")
        print(f"User Score-{score_u} amd Computer Score- {score_c}")
    t-=1
        


enter 1 for rock 2 for paper and 3 for scissors 1


Computer wins
Your score-
User Score-0 amd Computer Score- 0


enter 1 for rock 2 for paper and 3 for scissors 0


Computer wins
Your score-
User Score-0 amd Computer Score- 0


KeyboardInterrupt: Interrupted by user